url: http://wkang.github.com
title: "{ Kang Wen }"
simple_search: http://google.com/search
permalink: /:categories/:title/
markdown: kramdown
kramdown:
 use_coderay: true
 coderay:
  coderay_line_numbers:
paginate: 10
